manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/DangUoc/zmk
    - name: infused-kim
      url-base: https://github.com/infused-kim
  projects:
    - name: zmk
      remote: infused-kim
      revision: sofle
      import: app/west.yml
  self:
    path: config
